### ISSUE TITLE
Feature Request: Includes Folder

### ISSUE THREAD

**Issue by AmarettoSlim** [martin9700/PSModuleBuild#14]
Hi @martin9700  - 

Great module, thank you. I have a feature request, would it be possible to have PSModuleBuild check for a sub folder called 'includes' and copy it to the output along side the .psm1 & .psd1?

This would allow give developers a location to add any external resources (I'm thinking templates) and ensure they are included along side the module for local reference by functions.

Thanks!

**Comment by martin9700** [comment]
PSModuleBuild supports having external files, but only if the TargetPath is pointed inside the repository folder structure.  If the TargetPath is outside that it doesn't work.

Create a Include parameter to point to files/folders and have PSModuleBuild copy those to the TargetPath.

**Comment by martin9700** [comment]
Include has been added and published.  Please test and let me know how it goes.

**Comment by AmarettoSlim** [comment]
I tested the new -Include parameter passing in a folder called "includes", confirmed all contents within the includes folder were copied to the target path along with the modules and manifest files, thank you for the quick work @martin9700 !
